name: 'teradata_mig_poc'
version: '1.0.0'
config-version: 2

profile: 'databricks_transformation'  # This should match the profile name in profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
 teradata_mig_poc:
    marts:
      +materialized: table
      +format: iceberg